services:
  autchdb:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: Frontend
    ports:
      - "80:80"
    networks:
      - flixlnet
    depends_on:
      db:
        condition: service_started

  db:
    build: 
      context: .
      dockerfile: Dockerfile-db
    container_name: auadb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=root
      - COUCHDB_PASSWORD=root
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      - flixlnet

volumes:
  couchdb_data:

networks:
  flixlnet:
    driver: bridge
